f = open("database.txt", "r")
names = f.read()
result = ''.join(i for i in names if not i.isdigit())
result = result.replace("%", "")
result = result.replace(",", "")
result = result.replace(":", "")
result = result.replace("\t", "")
result = result.replace(" ", "")
result = result.replace("\n", ",")
# result = "\"" + result + "\""
f.close()
w = open("cleandb.txt", "w")
w.write(result)
w.close()
print(result)